/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';
import type { TrackObject } from './TrackObject';
import {
    TrackObjectFromJSON,
    TrackObjectFromJSONTyped,
    TrackObjectToJSON,
    TrackObjectToJSONTyped,
} from './TrackObject';

/**
 * 
 * @export
 * @interface ChangeTracksRequest
 */
export interface ChangeTracksRequest {
    /**
     * Map of track IDs to track objects for changing tracks
     * @type {{ [key: string]: TrackObject; }}
     * @memberof ChangeTracksRequest
     */
    tracks?: { [key: string]: TrackObject; };
    /**
     * 
     * @type {SessionDescription}
     * @memberof ChangeTracksRequest
     */
    sessionDescription?: SessionDescription;
}

/**
 * Check if a given object implements the ChangeTracksRequest interface.
 */
export function instanceOfChangeTracksRequest(value: object): value is ChangeTracksRequest {
    return true;
}

export function ChangeTracksRequestFromJSON(json: any): ChangeTracksRequest {
    return ChangeTracksRequestFromJSONTyped(json, false);
}

export function ChangeTracksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeTracksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tracks': json['tracks'] == null ? undefined : (mapValues(json['tracks'], TrackObjectFromJSON)),
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
    };
}

export function ChangeTracksRequestToJSON(json: any): ChangeTracksRequest {
    return ChangeTracksRequestToJSONTyped(json, false);
}

export function ChangeTracksRequestToJSONTyped(value?: ChangeTracksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tracks': value['tracks'] == null ? undefined : (mapValues(value['tracks'], TrackObjectToJSON)),
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
    };
}

