/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';
import type { CloseTrackObject } from './CloseTrackObject';
import {
    CloseTrackObjectFromJSON,
    CloseTrackObjectFromJSONTyped,
    CloseTrackObjectToJSON,
    CloseTrackObjectToJSONTyped,
} from './CloseTrackObject';

/**
 * 
 * @export
 * @interface CloseTracksRequest
 */
export interface CloseTracksRequest {
    /**
     * 
     * @type {SessionDescription}
     * @memberof CloseTracksRequest
     */
    sessionDescription?: SessionDescription;
    /**
     * 
     * @type {Array<CloseTrackObject>}
     * @memberof CloseTracksRequest
     */
    tracks?: Array<CloseTrackObject>;
    /**
     * True if you want to stop just the data flow for the tracks, no WebRTC renegotiation
     * @type {boolean}
     * @memberof CloseTracksRequest
     */
    force?: boolean;
}

/**
 * Check if a given object implements the CloseTracksRequest interface.
 */
export function instanceOfCloseTracksRequest(value: object): value is CloseTracksRequest {
    return true;
}

export function CloseTracksRequestFromJSON(json: any): CloseTracksRequest {
    return CloseTracksRequestFromJSONTyped(json, false);
}

export function CloseTracksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseTracksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(CloseTrackObjectFromJSON)),
        'force': json['force'] == null ? undefined : json['force'],
    };
}

export function CloseTracksRequestToJSON(json: any): CloseTracksRequest {
    return CloseTracksRequestToJSONTyped(json, false);
}

export function CloseTracksRequestToJSONTyped(value?: CloseTracksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(CloseTrackObjectToJSON)),
        'force': value['force'],
    };
}

