/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';
import type { CloseTracksResponseTracksInner } from './CloseTracksResponseTracksInner';
import {
    CloseTracksResponseTracksInnerFromJSON,
    CloseTracksResponseTracksInnerFromJSONTyped,
    CloseTracksResponseTracksInnerToJSON,
    CloseTracksResponseTracksInnerToJSONTyped,
} from './CloseTracksResponseTracksInner';

/**
 * 
 * @export
 * @interface CloseTracksResponse
 */
export interface CloseTracksResponse {
    /**
     * 
     * @type {string}
     * @memberof CloseTracksResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CloseTracksResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {SessionDescription}
     * @memberof CloseTracksResponse
     */
    sessionDescription?: SessionDescription;
    /**
     * 
     * @type {Array<CloseTracksResponseTracksInner>}
     * @memberof CloseTracksResponse
     */
    tracks?: Array<CloseTracksResponseTracksInner>;
    /**
     * 
     * @type {boolean}
     * @memberof CloseTracksResponse
     */
    requiresImmediateRenegotiation?: boolean;
}

/**
 * Check if a given object implements the CloseTracksResponse interface.
 */
export function instanceOfCloseTracksResponse(value: object): value is CloseTracksResponse {
    return true;
}

export function CloseTracksResponseFromJSON(json: any): CloseTracksResponse {
    return CloseTracksResponseFromJSONTyped(json, false);
}

export function CloseTracksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseTracksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(CloseTracksResponseTracksInnerFromJSON)),
        'requiresImmediateRenegotiation': json['requiresImmediateRenegotiation'] == null ? undefined : json['requiresImmediateRenegotiation'],
    };
}

export function CloseTracksResponseToJSON(json: any): CloseTracksResponse {
    return CloseTracksResponseToJSONTyped(json, false);
}

export function CloseTracksResponseToJSONTyped(value?: CloseTracksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(CloseTracksResponseTracksInnerToJSON)),
        'requiresImmediateRenegotiation': value['requiresImmediateRenegotiation'],
    };
}

