/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloseTracksResponseTracksInner
 */
export interface CloseTracksResponseTracksInner {
    /**
     * mid associated to the track's transceiver to close
     * @type {string}
     * @memberof CloseTracksResponseTracksInner
     */
    mid?: string;
    /**
     * 
     * @type {string}
     * @memberof CloseTracksResponseTracksInner
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CloseTracksResponseTracksInner
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the CloseTracksResponseTracksInner interface.
 */
export function instanceOfCloseTracksResponseTracksInner(value: object): value is CloseTracksResponseTracksInner {
    return true;
}

export function CloseTracksResponseTracksInnerFromJSON(json: any): CloseTracksResponseTracksInner {
    return CloseTracksResponseTracksInnerFromJSONTyped(json, false);
}

export function CloseTracksResponseTracksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseTracksResponseTracksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'mid': json['mid'] == null ? undefined : json['mid'],
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
    };
}

export function CloseTracksResponseTracksInnerToJSON(json: any): CloseTracksResponseTracksInner {
    return CloseTracksResponseTracksInnerToJSONTyped(json, false);
}

export function CloseTracksResponseTracksInnerToJSONTyped(value?: CloseTracksResponseTracksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mid': value['mid'],
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
    };
}

