/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloseTrackObject
 */
export interface CloseTrackObject {
    /**
     * mid associated to the track's transceiver to close
     * @type {string}
     * @memberof CloseTrackObject
     */
    mid?: string;
}

/**
 * Check if a given object implements the CloseTrackObject interface.
 */
export function instanceOfCloseTrackObject(value: object): value is CloseTrackObject {
    return true;
}

export function CloseTrackObjectFromJSON(json: any): CloseTrackObject {
    return CloseTrackObjectFromJSONTyped(json, false);
}

export function CloseTrackObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseTrackObject {
    if (json == null) {
        return json;
    }
    return {
        
        'mid': json['mid'] == null ? undefined : json['mid'],
    };
}

export function CloseTrackObjectToJSON(json: any): CloseTrackObject {
    return CloseTrackObjectToJSONTyped(json, false);
}

export function CloseTrackObjectToJSONTyped(value?: CloseTrackObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mid': value['mid'],
    };
}

