/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackObjectSimulcast } from './TrackObjectSimulcast';
import {
    TrackObjectSimulcastFromJSON,
    TrackObjectSimulcastFromJSONTyped,
    TrackObjectSimulcastToJSON,
    TrackObjectSimulcastToJSONTyped,
} from './TrackObjectSimulcast';

/**
 * 
 * @export
 * @interface GetSessionStateResponseTracksInner
 */
export interface GetSessionStateResponseTracksInner {
    /**
     * If you want to share a track, it should be local. If you want to play a track shared by a remote agent, it should be remote
     * @type {string}
     * @memberof GetSessionStateResponseTracksInner
     */
    location?: GetSessionStateResponseTracksInnerLocationEnum;
    /**
     * mid associated to track's transceiver. It also can be prefixed with \# to reference an existing transceiver by its trackName
     * @type {string}
     * @memberof GetSessionStateResponseTracksInner
     */
    mid?: string;
    /**
     * Session ID of the track owner. It should be set for remote tracks only
     * @type {string}
     * @memberof GetSessionStateResponseTracksInner
     */
    sessionId?: string;
    /**
     * Given name for the track
     * @type {string}
     * @memberof GetSessionStateResponseTracksInner
     */
    trackName?: string;
    /**
     * Make the associated transceiver bidirectional. This option works only when the SFU generates the offer
     * @type {boolean}
     * @memberof GetSessionStateResponseTracksInner
     */
    bidirectionalMediaStream?: boolean;
    /**
     * Give a hint to the SFU about the transceiver kind. This is required when the SFU generates the offer
     * @type {string}
     * @memberof GetSessionStateResponseTracksInner
     */
    kind?: string;
    /**
     * 
     * @type {TrackObjectSimulcast}
     * @memberof GetSessionStateResponseTracksInner
     */
    simulcast?: TrackObjectSimulcast;
    /**
     * 
     * @type {string}
     * @memberof GetSessionStateResponseTracksInner
     */
    status?: GetSessionStateResponseTracksInnerStatusEnum;
}


/**
 * @export
 */
export const GetSessionStateResponseTracksInnerLocationEnum = {
    Local: 'local',
    Remote: 'remote'
} as const;
export type GetSessionStateResponseTracksInnerLocationEnum = typeof GetSessionStateResponseTracksInnerLocationEnum[keyof typeof GetSessionStateResponseTracksInnerLocationEnum];

/**
 * @export
 */
export const GetSessionStateResponseTracksInnerStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Waiting: 'waiting'
} as const;
export type GetSessionStateResponseTracksInnerStatusEnum = typeof GetSessionStateResponseTracksInnerStatusEnum[keyof typeof GetSessionStateResponseTracksInnerStatusEnum];


/**
 * Check if a given object implements the GetSessionStateResponseTracksInner interface.
 */
export function instanceOfGetSessionStateResponseTracksInner(value: object): value is GetSessionStateResponseTracksInner {
    return true;
}

export function GetSessionStateResponseTracksInnerFromJSON(json: any): GetSessionStateResponseTracksInner {
    return GetSessionStateResponseTracksInnerFromJSONTyped(json, false);
}

export function GetSessionStateResponseTracksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSessionStateResponseTracksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'] == null ? undefined : json['location'],
        'mid': json['mid'] == null ? undefined : json['mid'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'trackName': json['trackName'] == null ? undefined : json['trackName'],
        'bidirectionalMediaStream': json['bidirectionalMediaStream'] == null ? undefined : json['bidirectionalMediaStream'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'simulcast': json['simulcast'] == null ? undefined : TrackObjectSimulcastFromJSON(json['simulcast']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function GetSessionStateResponseTracksInnerToJSON(json: any): GetSessionStateResponseTracksInner {
    return GetSessionStateResponseTracksInnerToJSONTyped(json, false);
}

export function GetSessionStateResponseTracksInnerToJSONTyped(value?: GetSessionStateResponseTracksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': value['location'],
        'mid': value['mid'],
        'sessionId': value['sessionId'],
        'trackName': value['trackName'],
        'bidirectionalMediaStream': value['bidirectionalMediaStream'],
        'kind': value['kind'],
        'simulcast': TrackObjectSimulcastToJSON(value['simulcast']),
        'status': value['status'],
    };
}

