/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSessionStateResponseTracksInner } from './GetSessionStateResponseTracksInner';
import {
    GetSessionStateResponseTracksInnerFromJSON,
    GetSessionStateResponseTracksInnerFromJSONTyped,
    GetSessionStateResponseTracksInnerToJSON,
    GetSessionStateResponseTracksInnerToJSONTyped,
} from './GetSessionStateResponseTracksInner';

/**
 * 
 * @export
 * @interface GetSessionStateResponse
 */
export interface GetSessionStateResponse {
    /**
     * 
     * @type {string}
     * @memberof GetSessionStateResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSessionStateResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {Array<GetSessionStateResponseTracksInner>}
     * @memberof GetSessionStateResponse
     */
    tracks?: Array<GetSessionStateResponseTracksInner>;
}

/**
 * Check if a given object implements the GetSessionStateResponse interface.
 */
export function instanceOfGetSessionStateResponse(value: object): value is GetSessionStateResponse {
    return true;
}

export function GetSessionStateResponseFromJSON(json: any): GetSessionStateResponse {
    return GetSessionStateResponseFromJSONTyped(json, false);
}

export function GetSessionStateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSessionStateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(GetSessionStateResponseTracksInnerFromJSON)),
    };
}

export function GetSessionStateResponseToJSON(json: any): GetSessionStateResponse {
    return GetSessionStateResponseToJSONTyped(json, false);
}

export function GetSessionStateResponseToJSONTyped(value?: GetSessionStateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(GetSessionStateResponseTracksInnerToJSON)),
    };
}

