/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewSessionResponseSessionDescription } from './NewSessionResponseSessionDescription';
import {
    NewSessionResponseSessionDescriptionFromJSON,
    NewSessionResponseSessionDescriptionFromJSONTyped,
    NewSessionResponseSessionDescriptionToJSON,
    NewSessionResponseSessionDescriptionToJSONTyped,
} from './NewSessionResponseSessionDescription';

/**
 * 
 * @export
 * @interface NewSessionResponse
 */
export interface NewSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof NewSessionResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSessionResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {NewSessionResponseSessionDescription}
     * @memberof NewSessionResponse
     */
    sessionDescription?: NewSessionResponseSessionDescription;
    /**
     * 
     * @type {string}
     * @memberof NewSessionResponse
     */
    sessionId: string;
}

/**
 * Check if a given object implements the NewSessionResponse interface.
 */
export function instanceOfNewSessionResponse(value: object): value is NewSessionResponse {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function NewSessionResponseFromJSON(json: any): NewSessionResponse {
    return NewSessionResponseFromJSONTyped(json, false);
}

export function NewSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'sessionDescription': json['sessionDescription'] == null ? undefined : NewSessionResponseSessionDescriptionFromJSON(json['sessionDescription']),
        'sessionId': json['sessionId'],
    };
}

export function NewSessionResponseToJSON(json: any): NewSessionResponse {
    return NewSessionResponseToJSONTyped(json, false);
}

export function NewSessionResponseToJSONTyped(value?: NewSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
        'sessionDescription': NewSessionResponseSessionDescriptionToJSON(value['sessionDescription']),
        'sessionId': value['sessionId'],
    };
}

