/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';

/**
 * 
 * @export
 * @interface NewSessionRequest
 */
export interface NewSessionRequest {
    /**
     * 
     * @type {SessionDescription}
     * @memberof NewSessionRequest
     */
    sessionDescription?: SessionDescription;
}

/**
 * Check if a given object implements the NewSessionRequest interface.
 */
export function instanceOfNewSessionRequest(value: object): value is NewSessionRequest {
    return true;
}

export function NewSessionRequestFromJSON(json: any): NewSessionRequest {
    return NewSessionRequestFromJSONTyped(json, false);
}

export function NewSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
    };
}

export function NewSessionRequestToJSON(json: any): NewSessionRequest {
    return NewSessionRequestToJSONTyped(json, false);
}

export function NewSessionRequestToJSONTyped(value?: NewSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
    };
}

