/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewSessionResponseSessionDescription
 */
export interface NewSessionResponseSessionDescription {
    /**
     * 
     * @type {string}
     * @memberof NewSessionResponseSessionDescription
     */
    sdp?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSessionResponseSessionDescription
     */
    type?: NewSessionResponseSessionDescriptionTypeEnum;
}


/**
 * @export
 */
export const NewSessionResponseSessionDescriptionTypeEnum = {
    Answer: 'answer',
    Offer: 'offer'
} as const;
export type NewSessionResponseSessionDescriptionTypeEnum = typeof NewSessionResponseSessionDescriptionTypeEnum[keyof typeof NewSessionResponseSessionDescriptionTypeEnum];


/**
 * Check if a given object implements the NewSessionResponseSessionDescription interface.
 */
export function instanceOfNewSessionResponseSessionDescription(value: object): value is NewSessionResponseSessionDescription {
    return true;
}

export function NewSessionResponseSessionDescriptionFromJSON(json: any): NewSessionResponseSessionDescription {
    return NewSessionResponseSessionDescriptionFromJSONTyped(json, false);
}

export function NewSessionResponseSessionDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSessionResponseSessionDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'sdp': json['sdp'] == null ? undefined : json['sdp'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function NewSessionResponseSessionDescriptionToJSON(json: any): NewSessionResponseSessionDescription {
    return NewSessionResponseSessionDescriptionToJSONTyped(json, false);
}

export function NewSessionResponseSessionDescriptionToJSONTyped(value?: NewSessionResponseSessionDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sdp': value['sdp'],
        'type': value['type'],
    };
}

