/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';

/**
 * 
 * @export
 * @interface RenegotiateResponse
 */
export interface RenegotiateResponse {
    /**
     * 
     * @type {string}
     * @memberof RenegotiateResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RenegotiateResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {SessionDescription}
     * @memberof RenegotiateResponse
     */
    sessionDescription?: SessionDescription;
}

/**
 * Check if a given object implements the RenegotiateResponse interface.
 */
export function instanceOfRenegotiateResponse(value: object): value is RenegotiateResponse {
    return true;
}

export function RenegotiateResponseFromJSON(json: any): RenegotiateResponse {
    return RenegotiateResponseFromJSONTyped(json, false);
}

export function RenegotiateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenegotiateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
    };
}

export function RenegotiateResponseToJSON(json: any): RenegotiateResponse {
    return RenegotiateResponseToJSONTyped(json, false);
}

export function RenegotiateResponseToJSONTyped(value?: RenegotiateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
    };
}

