/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';

/**
 * 
 * @export
 * @interface RenegotiateRequest
 */
export interface RenegotiateRequest {
    /**
     * 
     * @type {SessionDescription}
     * @memberof RenegotiateRequest
     */
    sessionDescription?: SessionDescription;
}

/**
 * Check if a given object implements the RenegotiateRequest interface.
 */
export function instanceOfRenegotiateRequest(value: object): value is RenegotiateRequest {
    return true;
}

export function RenegotiateRequestFromJSON(json: any): RenegotiateRequest {
    return RenegotiateRequestFromJSONTyped(json, false);
}

export function RenegotiateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenegotiateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
    };
}

export function RenegotiateRequestToJSON(json: any): RenegotiateRequest {
    return RenegotiateRequestToJSONTyped(json, false);
}

export function RenegotiateRequestToJSONTyped(value?: RenegotiateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
    };
}

