/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionDescription
 */
export interface SessionDescription {
    /**
     * 
     * @type {string}
     * @memberof SessionDescription
     */
    sdp?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionDescription
     */
    type?: SessionDescriptionTypeEnum;
}


/**
 * @export
 */
export const SessionDescriptionTypeEnum = {
    Answer: 'answer',
    Offer: 'offer'
} as const;
export type SessionDescriptionTypeEnum = typeof SessionDescriptionTypeEnum[keyof typeof SessionDescriptionTypeEnum];


/**
 * Check if a given object implements the SessionDescription interface.
 */
export function instanceOfSessionDescription(value: object): value is SessionDescription {
    return true;
}

export function SessionDescriptionFromJSON(json: any): SessionDescription {
    return SessionDescriptionFromJSONTyped(json, false);
}

export function SessionDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'sdp': json['sdp'] == null ? undefined : json['sdp'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SessionDescriptionToJSON(json: any): SessionDescription {
    return SessionDescriptionToJSONTyped(json, false);
}

export function SessionDescriptionToJSONTyped(value?: SessionDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sdp': value['sdp'],
        'type': value['type'],
    };
}

