/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';
import type { TrackObject } from './TrackObject';
import {
    TrackObjectFromJSON,
    TrackObjectFromJSONTyped,
    TrackObjectToJSON,
    TrackObjectToJSONTyped,
} from './TrackObject';

/**
 * 
 * @export
 * @interface TracksRequest
 */
export interface TracksRequest {
    /**
     * 
     * @type {SessionDescription}
     * @memberof TracksRequest
     */
    sessionDescription?: SessionDescription;
    /**
     * 
     * @type {Array<TrackObject>}
     * @memberof TracksRequest
     */
    tracks?: Array<TrackObject>;
    /**
     * Assign a random track name to any new track in the offered SDP
     * @type {boolean}
     * @memberof TracksRequest
     */
    autoDiscover?: boolean;
}

/**
 * Check if a given object implements the TracksRequest interface.
 */
export function instanceOfTracksRequest(value: object): value is TracksRequest {
    return true;
}

export function TracksRequestFromJSON(json: any): TracksRequest {
    return TracksRequestFromJSONTyped(json, false);
}

export function TracksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TrackObjectFromJSON)),
        'autoDiscover': json['autoDiscover'] == null ? undefined : json['autoDiscover'],
    };
}

export function TracksRequestToJSON(json: any): TracksRequest {
    return TracksRequestToJSONTyped(json, false);
}

export function TracksRequestToJSONTyped(value?: TracksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TrackObjectToJSON)),
        'autoDiscover': value['autoDiscover'],
    };
}

