/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackObjectSimulcast } from './TrackObjectSimulcast';
import {
    TrackObjectSimulcastFromJSON,
    TrackObjectSimulcastFromJSONTyped,
    TrackObjectSimulcastToJSON,
    TrackObjectSimulcastToJSONTyped,
} from './TrackObjectSimulcast';

/**
 * 
 * @export
 * @interface TracksResponseTracksInner
 */
export interface TracksResponseTracksInner {
    /**
     * If you want to share a track, it should be local. If you want to play a track shared by a remote agent, it should be remote
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    location?: TracksResponseTracksInnerLocationEnum;
    /**
     * mid associated to track's transceiver. It also can be prefixed with \# to reference an existing transceiver by its trackName
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    mid?: string;
    /**
     * Session ID of the track owner. It should be set for remote tracks only
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    sessionId?: string;
    /**
     * Given name for the track
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    trackName?: string;
    /**
     * Make the associated transceiver bidirectional. This option works only when the SFU generates the offer
     * @type {boolean}
     * @memberof TracksResponseTracksInner
     */
    bidirectionalMediaStream?: boolean;
    /**
     * Give a hint to the SFU about the transceiver kind. This is required when the SFU generates the offer
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    kind?: string;
    /**
     * 
     * @type {TrackObjectSimulcast}
     * @memberof TracksResponseTracksInner
     */
    simulcast?: TrackObjectSimulcast;
    /**
     * 
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TracksResponseTracksInner
     */
    errorDescription?: string;
}


/**
 * @export
 */
export const TracksResponseTracksInnerLocationEnum = {
    Local: 'local',
    Remote: 'remote'
} as const;
export type TracksResponseTracksInnerLocationEnum = typeof TracksResponseTracksInnerLocationEnum[keyof typeof TracksResponseTracksInnerLocationEnum];


/**
 * Check if a given object implements the TracksResponseTracksInner interface.
 */
export function instanceOfTracksResponseTracksInner(value: object): value is TracksResponseTracksInner {
    return true;
}

export function TracksResponseTracksInnerFromJSON(json: any): TracksResponseTracksInner {
    return TracksResponseTracksInnerFromJSONTyped(json, false);
}

export function TracksResponseTracksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracksResponseTracksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'] == null ? undefined : json['location'],
        'mid': json['mid'] == null ? undefined : json['mid'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'trackName': json['trackName'] == null ? undefined : json['trackName'],
        'bidirectionalMediaStream': json['bidirectionalMediaStream'] == null ? undefined : json['bidirectionalMediaStream'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'simulcast': json['simulcast'] == null ? undefined : TrackObjectSimulcastFromJSON(json['simulcast']),
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
    };
}

export function TracksResponseTracksInnerToJSON(json: any): TracksResponseTracksInner {
    return TracksResponseTracksInnerToJSONTyped(json, false);
}

export function TracksResponseTracksInnerToJSONTyped(value?: TracksResponseTracksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': value['location'],
        'mid': value['mid'],
        'sessionId': value['sessionId'],
        'trackName': value['trackName'],
        'bidirectionalMediaStream': value['bidirectionalMediaStream'],
        'kind': value['kind'],
        'simulcast': TrackObjectSimulcastToJSON(value['simulcast']),
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
    };
}

