/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simulcast configuration for the track
 * @export
 * @interface TrackObjectSimulcast
 */
export interface TrackObjectSimulcast {
    /**
     * Preferred RID for simulcast streams
     * @type {string}
     * @memberof TrackObjectSimulcast
     */
    preferredRid?: string;
    /**
     * Controls what happens if there is not enough network resources available to send the preferredRid. 'none' means keep sending even if not enough bandwidth, 'asciibetical' uses a-z order to determine priority where a is most desirable and z is least desirable.
     * @type {string}
     * @memberof TrackObjectSimulcast
     */
    priorityOrdering?: TrackObjectSimulcastPriorityOrderingEnum;
    /**
     * Controls what happens when the rid currently being used or preferredRid is no longer being sent by the publisher. 'none' means do nothing, 'asciibetical' uses the next available layer after sorting the layers a-z.
     * @type {string}
     * @memberof TrackObjectSimulcast
     */
    ridNotAvailable?: TrackObjectSimulcastRidNotAvailableEnum;
}


/**
 * @export
 */
export const TrackObjectSimulcastPriorityOrderingEnum = {
    None: 'none',
    Asciibetical: 'asciibetical'
} as const;
export type TrackObjectSimulcastPriorityOrderingEnum = typeof TrackObjectSimulcastPriorityOrderingEnum[keyof typeof TrackObjectSimulcastPriorityOrderingEnum];

/**
 * @export
 */
export const TrackObjectSimulcastRidNotAvailableEnum = {
    None: 'none',
    Asciibetical: 'asciibetical'
} as const;
export type TrackObjectSimulcastRidNotAvailableEnum = typeof TrackObjectSimulcastRidNotAvailableEnum[keyof typeof TrackObjectSimulcastRidNotAvailableEnum];


/**
 * Check if a given object implements the TrackObjectSimulcast interface.
 */
export function instanceOfTrackObjectSimulcast(value: object): value is TrackObjectSimulcast {
    return true;
}

export function TrackObjectSimulcastFromJSON(json: any): TrackObjectSimulcast {
    return TrackObjectSimulcastFromJSONTyped(json, false);
}

export function TrackObjectSimulcastFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackObjectSimulcast {
    if (json == null) {
        return json;
    }
    return {
        
        'preferredRid': json['preferredRid'] == null ? undefined : json['preferredRid'],
        'priorityOrdering': json['priorityOrdering'] == null ? undefined : json['priorityOrdering'],
        'ridNotAvailable': json['ridNotAvailable'] == null ? undefined : json['ridNotAvailable'],
    };
}

export function TrackObjectSimulcastToJSON(json: any): TrackObjectSimulcast {
    return TrackObjectSimulcastToJSONTyped(json, false);
}

export function TrackObjectSimulcastToJSONTyped(value?: TrackObjectSimulcast | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preferredRid': value['preferredRid'],
        'priorityOrdering': value['priorityOrdering'],
        'ridNotAvailable': value['ridNotAvailable'],
    };
}

