/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TracksResponseTracksInner } from './TracksResponseTracksInner';
import {
    TracksResponseTracksInnerFromJSON,
    TracksResponseTracksInnerFromJSONTyped,
    TracksResponseTracksInnerToJSON,
    TracksResponseTracksInnerToJSONTyped,
} from './TracksResponseTracksInner';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';

/**
 * 
 * @export
 * @interface TracksResponse
 */
export interface TracksResponse {
    /**
     * 
     * @type {string}
     * @memberof TracksResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TracksResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TracksResponse
     */
    requiresImmediateRenegotiation?: boolean;
    /**
     * 
     * @type {SessionDescription}
     * @memberof TracksResponse
     */
    sessionDescription?: SessionDescription;
    /**
     * 
     * @type {Array<TracksResponseTracksInner>}
     * @memberof TracksResponse
     */
    tracks?: Array<TracksResponseTracksInner>;
}

/**
 * Check if a given object implements the TracksResponse interface.
 */
export function instanceOfTracksResponse(value: object): value is TracksResponse {
    return true;
}

export function TracksResponseFromJSON(json: any): TracksResponse {
    return TracksResponseFromJSONTyped(json, false);
}

export function TracksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'requiresImmediateRenegotiation': json['requiresImmediateRenegotiation'] == null ? undefined : json['requiresImmediateRenegotiation'],
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TracksResponseTracksInnerFromJSON)),
    };
}

export function TracksResponseToJSON(json: any): TracksResponse {
    return TracksResponseToJSONTyped(json, false);
}

export function TracksResponseToJSONTyped(value?: TracksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
        'requiresImmediateRenegotiation': value['requiresImmediateRenegotiation'],
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TracksResponseTracksInnerToJSON)),
    };
}

