/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TracksResponseTracksInner } from './TracksResponseTracksInner';
import {
    TracksResponseTracksInnerFromJSON,
    TracksResponseTracksInnerFromJSONTyped,
    TracksResponseTracksInnerToJSON,
    TracksResponseTracksInnerToJSONTyped,
} from './TracksResponseTracksInner';

/**
 * 
 * @export
 * @interface UpdateTracksResponse
 */
export interface UpdateTracksResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateTracksResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTracksResponse
     */
    errorDescription?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTracksResponse
     */
    requiresImmediateRenegotiation?: boolean;
    /**
     * Array of track objects with results
     * @type {Array<TracksResponseTracksInner>}
     * @memberof UpdateTracksResponse
     */
    tracks?: Array<TracksResponseTracksInner>;
}

/**
 * Check if a given object implements the UpdateTracksResponse interface.
 */
export function instanceOfUpdateTracksResponse(value: object): value is UpdateTracksResponse {
    return true;
}

export function UpdateTracksResponseFromJSON(json: any): UpdateTracksResponse {
    return UpdateTracksResponseFromJSONTyped(json, false);
}

export function UpdateTracksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTracksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorDescription': json['errorDescription'] == null ? undefined : json['errorDescription'],
        'requiresImmediateRenegotiation': json['requiresImmediateRenegotiation'] == null ? undefined : json['requiresImmediateRenegotiation'],
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TracksResponseTracksInnerFromJSON)),
    };
}

export function UpdateTracksResponseToJSON(json: any): UpdateTracksResponse {
    return UpdateTracksResponseToJSONTyped(json, false);
}

export function UpdateTracksResponseToJSONTyped(value?: UpdateTracksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': value['errorCode'],
        'errorDescription': value['errorDescription'],
        'requiresImmediateRenegotiation': value['requiresImmediateRenegotiation'],
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TracksResponseTracksInnerToJSON)),
    };
}

