/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionDescription } from './SessionDescription';
import {
    SessionDescriptionFromJSON,
    SessionDescriptionFromJSONTyped,
    SessionDescriptionToJSON,
    SessionDescriptionToJSONTyped,
} from './SessionDescription';
import type { TrackObject } from './TrackObject';
import {
    TrackObjectFromJSON,
    TrackObjectFromJSONTyped,
    TrackObjectToJSON,
    TrackObjectToJSONTyped,
} from './TrackObject';

/**
 * 
 * @export
 * @interface UpdateTracksRequest
 */
export interface UpdateTracksRequest {
    /**
     * Array of track objects for updating tracks
     * @type {Array<TrackObject>}
     * @memberof UpdateTracksRequest
     */
    tracks?: Array<TrackObject>;
    /**
     * 
     * @type {SessionDescription}
     * @memberof UpdateTracksRequest
     */
    sessionDescription?: SessionDescription;
}

/**
 * Check if a given object implements the UpdateTracksRequest interface.
 */
export function instanceOfUpdateTracksRequest(value: object): value is UpdateTracksRequest {
    return true;
}

export function UpdateTracksRequestFromJSON(json: any): UpdateTracksRequest {
    return UpdateTracksRequestFromJSONTyped(json, false);
}

export function UpdateTracksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTracksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TrackObjectFromJSON)),
        'sessionDescription': json['sessionDescription'] == null ? undefined : SessionDescriptionFromJSON(json['sessionDescription']),
    };
}

export function UpdateTracksRequestToJSON(json: any): UpdateTracksRequest {
    return UpdateTracksRequestToJSONTyped(json, false);
}

export function UpdateTracksRequestToJSONTyped(value?: UpdateTracksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TrackObjectToJSON)),
        'sessionDescription': SessionDescriptionToJSON(value['sessionDescription']),
    };
}

