/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings --include-runtime false` (hash: 74c3a49fcd7924ad196d7fe1cc06845a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env {
		LIVE_DB: D1Database;
		CALLS_APP_ID: string;
		CALLS_APP_SECRET: string;
		JWT_SECRET: string;
		DISCORD_CLIENT_ID: string;
		DISCORD_CLIENT_SECRET: string;
		AUTHORIZED_GUILD_ID: string;
		ENVIRONMENT: string;
		LIVE_TOKEN_PEPPER: string;
		NOTIFICATIONS_DISCORD_WEBHOOK_URL: string;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
