/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings --include-runtime false --strict-vars=false` (hash: bd652cfbd982d6eb490bf9a0e51cc2df)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env {
		LIVE_DB: D1Database;
		ENVIRONMENT: string;
		LOG_LEVEL: string;
		AUTHORIZED_GUILD_ID: string;
		CALLS_APP_ID: string;
		CALLS_APP_SECRET: string;
		DISCORD_CLIENT_ID: string;
		DISCORD_CLIENT_SECRET: string;
		JWT_SECRET: string;
		LIVE_TOKEN_PEPPER: string;
		NOTIFICATIONS_DISCORD_WEBHOOK_URL: string;
		TURN_KEY_API_TOKEN: string;
		TURN_KEY_ID: string;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
