/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TracksRequest,
  TracksResponse,
} from '../models/index';
import {
    TracksRequestFromJSON,
    TracksRequestToJSON,
    TracksResponseFromJSON,
    TracksResponseToJSON,
} from '../models/index';

export interface AppsAppIdSessionsSessionIdTracksNewPostRequest {
    appId: string;
    sessionId: string;
    tracksRequest?: TracksRequest;
}

/**
 * 
 */
export class AddATrackApi extends runtime.BaseAPI {

    /**
     * Solve the given track object(s) and add the track(s) to the WebRTC session
     */
    async appsAppIdSessionsSessionIdTracksNewPostRaw(requestParameters: AppsAppIdSessionsSessionIdTracksNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TracksResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdSessionsSessionIdTracksNewPost().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling appsAppIdSessionsSessionIdTracksNewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("secret", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/apps/{appId}/sessions/{sessionId}/tracks/new`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TracksRequestToJSON(requestParameters['tracksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TracksResponseFromJSON(jsonValue));
    }

    /**
     * Solve the given track object(s) and add the track(s) to the WebRTC session
     */
    async appsAppIdSessionsSessionIdTracksNewPost(requestParameters: AppsAppIdSessionsSessionIdTracksNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TracksResponse> {
        const response = await this.appsAppIdSessionsSessionIdTracksNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
