/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UpdateTracksRequest,
  UpdateTracksResponse,
} from '../models/index';
import {
    UpdateTracksRequestFromJSON,
    UpdateTracksRequestToJSON,
    UpdateTracksResponseFromJSON,
    UpdateTracksResponseToJSON,
} from '../models/index';

export interface AppsAppIdSessionsSessionIdTracksUpdatePutRequest {
    appId: string;
    sessionId: string;
    updateTracksRequest?: UpdateTracksRequest;
}

/**
 * 
 */
export class ChangeTracksApi extends runtime.BaseAPI {

    /**
     * Change tracks by reusing existing transceivers
     */
    async appsAppIdSessionsSessionIdTracksUpdatePutRaw(requestParameters: AppsAppIdSessionsSessionIdTracksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateTracksResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdSessionsSessionIdTracksUpdatePut().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling appsAppIdSessionsSessionIdTracksUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("secret", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/apps/{appId}/sessions/{sessionId}/tracks/update`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTracksRequestToJSON(requestParameters['updateTracksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateTracksResponseFromJSON(jsonValue));
    }

    /**
     * Change tracks by reusing existing transceivers
     */
    async appsAppIdSessionsSessionIdTracksUpdatePut(requestParameters: AppsAppIdSessionsSessionIdTracksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateTracksResponse> {
        const response = await this.appsAppIdSessionsSessionIdTracksUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
