/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CloseTracksRequest,
  CloseTracksResponse,
} from '../models/index';
import {
    CloseTracksRequestFromJSON,
    CloseTracksRequestToJSON,
    CloseTracksResponseFromJSON,
    CloseTracksResponseToJSON,
} from '../models/index';

export interface AppsAppIdSessionsSessionIdTracksClosePutRequest {
    appId: string;
    sessionId: string;
    closeTracksRequest?: CloseTracksRequest;
}

/**
 * 
 */
export class CloseATrackApi extends runtime.BaseAPI {

    /**
     * Close a local or remote track
     */
    async appsAppIdSessionsSessionIdTracksClosePutRaw(requestParameters: AppsAppIdSessionsSessionIdTracksClosePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CloseTracksResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdSessionsSessionIdTracksClosePut().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling appsAppIdSessionsSessionIdTracksClosePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("secret", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/apps/{appId}/sessions/{sessionId}/tracks/close`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CloseTracksRequestToJSON(requestParameters['closeTracksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CloseTracksResponseFromJSON(jsonValue));
    }

    /**
     * Close a local or remote track
     */
    async appsAppIdSessionsSessionIdTracksClosePut(requestParameters: AppsAppIdSessionsSessionIdTracksClosePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CloseTracksResponse> {
        const response = await this.appsAppIdSessionsSessionIdTracksClosePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
