/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSessionStateResponse,
} from '../models/index';
import {
    GetSessionStateResponseFromJSON,
    GetSessionStateResponseToJSON,
} from '../models/index';

export interface AppsAppIdSessionsSessionIdGetRequest {
    appId: string;
    sessionId: string;
}

/**
 * 
 */
export class GetSessionStateApi extends runtime.BaseAPI {

    /**
     * Return the list of tracks associated to the session
     */
    async appsAppIdSessionsSessionIdGetRaw(requestParameters: AppsAppIdSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSessionStateResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdSessionsSessionIdGet().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling appsAppIdSessionsSessionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("secret", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/apps/{appId}/sessions/{sessionId}`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSessionStateResponseFromJSON(jsonValue));
    }

    /**
     * Return the list of tracks associated to the session
     */
    async appsAppIdSessionsSessionIdGet(requestParameters: AppsAppIdSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSessionStateResponse> {
        const response = await this.appsAppIdSessionsSessionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
