/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NewSessionResponse,
} from '../models/index';
import {
    NewSessionResponseFromJSON,
    NewSessionResponseToJSON,
} from '../models/index';

export interface AppsAppIdSessionsNewPostRequest {
    appId: string;
    thirdparty?: boolean;
    correlationId?: string;
}

/**
 * 
 */
export class NewSessionApi extends runtime.BaseAPI {

    /**
     * Create a new PeerConnection
     */
    async appsAppIdSessionsNewPostRaw(requestParameters: AppsAppIdSessionsNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewSessionResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdSessionsNewPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['thirdparty'] != null) {
            queryParameters['thirdparty'] = requestParameters['thirdparty'];
        }

        if (requestParameters['correlationId'] != null) {
            queryParameters['correlationId'] = requestParameters['correlationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("secret", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/apps/{appId}/sessions/new`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create a new PeerConnection
     */
    async appsAppIdSessionsNewPost(requestParameters: AppsAppIdSessionsNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewSessionResponse> {
        const response = await this.appsAppIdSessionsNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
