/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare Realtime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RenegotiateRequest,
  RenegotiateResponse,
} from '../models/index';
import {
    RenegotiateRequestFromJSON,
    RenegotiateRequestToJSON,
    RenegotiateResponseFromJSON,
    RenegotiateResponseToJSON,
} from '../models/index';

export interface AppsAppIdSessionsSessionIdRenegotiatePutRequest {
    appId: string;
    sessionId: string;
    renegotiateRequest?: RenegotiateRequest;
}

/**
 * 
 */
export class RenegotiateWebRTCSessionApi extends runtime.BaseAPI {

    /**
     * When a previous response has requiresImmediateRenegotiation, you must renegotiate
     */
    async appsAppIdSessionsSessionIdRenegotiatePutRaw(requestParameters: AppsAppIdSessionsSessionIdRenegotiatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenegotiateResponse>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdSessionsSessionIdRenegotiatePut().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling appsAppIdSessionsSessionIdRenegotiatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("secret", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/apps/{appId}/sessions/{sessionId}/renegotiate`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RenegotiateRequestToJSON(requestParameters['renegotiateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenegotiateResponseFromJSON(jsonValue));
    }

    /**
     * When a previous response has requiresImmediateRenegotiation, you must renegotiate
     */
    async appsAppIdSessionsSessionIdRenegotiatePut(requestParameters: AppsAppIdSessionsSessionIdRenegotiatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenegotiateResponse> {
        const response = await this.appsAppIdSessionsSessionIdRenegotiatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
